steps:
  - label: ":requirements: Install requirements"
    command: "pip install -r requirements.txt"
  
  - label: ":unit test: Run unit tests"
    command: "python -m unittest tests/test_preprocessing.py -v"